#!/bin/sh

# colors && font #
col_gray1="#222222"
col_gray2="#444444"
col_gray3="#bbbbbb"
col_gray4="#eeeeee"
col_cyan="#484e5f"
dmenufont="Hack:size=12"
choice="VGA\nHDMI"

position1() {
	status="left\nright\nup\ndown\noff\nmiroir"
	chosen=$(echo -e "$status" | dmenu -p "displayPosition" \
	-nb $col_gray1 -sb $col_cyan -fn $dmenufont)

	case "$chosen" in
        	left) xrandr --output DP1 --left-of eDP1 --auto;;
        	right) xrandr --output DP1 --right-of eDP1 --auto;;
        	up) xrandr --output DP1 --above eDP1 --auto;;
        	down) xrandr --output DP1 --below eDP1 --auto;;
        	off) xrandr --output DP1 --off;;
        	miroir) xrandr --output DP1 --auto;;
	esac
}

position2() {
        status="left\nright\nup\ndown\noff\nmiroir"
        chosen=$(echo -e "$status" | dmenu -p "displayPosition" \
        -nb $col_gray1 -sb $col_cyan -fn $dmenufont)

        case "$chosen" in
                left) xrandr --output HDMI1 --left-of eDP1 --auto;;
                right) xrandr --output HDMI1 --right-of eDP1 --auto;;
                up) xrandr --output HDMI1 --above eDP1 --auto;;
                down) xrandr --output HDMI1 --below eDP1 --auto;;
                off) xrandr --output HDMI1 --off;;
                miroir) xrandr --output HDMI1 --auto;;
        esac
}

chosen=$(echo -e $choice | dmenu -p "displayChoice" \
-nb $col_gray1 -sb $col_cyan -fn $dmenufont)

case "$chosen" in
	VGA) $(position1);;
	HDMI) $(position2);;
esac
