#!/bin/sh
# REQUIRES FONT-AWESOME PACKAGE TO WORK PROPERLY AND ALSO PATCHES FROMS DWM

dte() {
    dte="$(date +"%a, %b %d")"
    printf "%s" "   $dte"
}

hour() {
    hour="$(date +%H:%M:%S)"
    printf "%s" "   $hour "
}

bat() {
    stringContain() { [ -z "${2##*$1*}" ] && { [ -z "$1" ] || [ -n "$2" ] ;} ; }
    battery="$(cat /sys/class/power_supply/BAT1/capacity)"
    status="$(cat /sys/class/power_supply/BAT1/status)"

    if stringContain "Charging" "$status"; then
        printf "%s" "   $battery%"
    else
        printf "%s" "   $battery%"
    fi

}

sound() {
    sContain() { [ -z "${2##*$1*}" ] && { [ -z "$1" ] || [ -n "$2" ] ;} ; }
    vol="$(amixer sget Master | grep 'Front Left:' | awk -F'[][]' '{print $2 }')"
    status="$(amixer sget Master | grep 'Front Right:' | awk -F'[][]' '{print $4 }')"

    if sContain "off" "$status"; then
        printf "%s" "   $vol"
    else
        printf "%s" "   $vol"
    fi
}

micro() {
    sContain() { [ -z "${2##*$1*}" ] && { [ -z "$1" ] || [ -n "$2" ] ;} ; }
    status="$(amixer sget Capture | grep 'Front Left:' | awk -F'[][]' '{print $4 }')"

    if sContain "off" "$status"; then
        printf "%s" "   off"
    else
        printf "%s" "   on"
    fi
}

blue() {
    if rfkill list bluetooth | grep -q 'yes$' ; then 
        rfkill unblock bluetooth
        printf "%s" "  off"
    else
        rfkill block bluetooth
        printf "%s" "  on"
    fi
}

mem() {
    mem="$(free -h | awk '/Mem:/{printf $3}')"
    printf "%s" " $mem"
}

cpu() {
    cpu="$(mpstat 1 5 | awk 'END{printf("%.2f%"), 100-$NF}')"
    printf "%s" "  $cpu"
}

temp() {
    tp="$(sensors | awk '/temp1/ {printf $2}')"
    printf "%s" "  $tp°C"
}

wifi() {
    wget -q --spider http://google.com
    if [ $? -eq 0 ]; then
        printf "%s" "   on"
    else
        printf "%s" "   off"
    fi
}

while true; do
    xsetroot -name " ^b#222222^$(blue) ^b#4b5263^$(wifi) ^b#222222^$(micro) ^b#4b5263^$(sound) ^b#222222^$(bat) ^b#4b5263^$(dte) ^b#222222^$(hour)"
    sleep 3s
done
