#!/bin/sh

choices="poweroff\nreboot\nlogout\nsuspend"
chosen=$(echo -e "$choices" | dmenu -p "Options:")
case "$chosen" in
	poweroff) poweroff;;
	reboot) reboot;;
	logout) pkill dwm;;
	suspend) systemctl suspend;;
esac

