#!/bin/sh

resolution() {
    choice="hd\nfhd\nqhd\nuhd"
    chosen=$(echo -e $choice | dmenu -p "Resolution :")
    case "$chosen" in
        hd) echo -e "1280x720";;
        fhd) echo -e "1920x1080";;
        qhd) echo -e "2560x1440";;
        uhd) echo -e "3840x2160";;
    esac
}

audio() {
        choice="Yes\nNo"
        chosen=$(echo -e $choice | dmenu -p "Audio :")

        case "$chosen" in
                Yes) echo -e "-f alsa -i default ";;
                No) echo -e " ";;
        esac
}

output() {
    echo $(dmenu -p "Enter output:")
}

monitor() {
        choice="laptop\nmonitor"
        chosen=$(echo -e $choice | dmenu -p "Screen :")
        case "$chosen" in
                laptop) echo -e ":0.0 ";;
                monitor) echo -e ":0.0+1920 ";;
        esac
}

main() {
    cmd="ffmpeg -video_size "
    frame=" -framerate 60"
    grap=" -f x11grab -i "
    dir=" /home/rr/Medias/"
    res="1920x1080"

    $cmd$res$framerate$grap$(monitor)$(audio)$dir$(output)
}

$(main)
